[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

[tool.ruff.format]
# Apply Black like config
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = false
docstring-code-line-length = "dynamic"
line-ending = "auto"

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "httptest.*"
ignore_missing_imports = true
