# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('issuer', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name=b'Issuer')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asap_issuers', to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'verbose_name': 'Issuer',
                'verbose_name_plural': 'Issuers',
            },
        ),
    ]
